version: "3.3"
services:
  db:
    image: postgres:14.3
    ports:
      - "5432:5432"
    volumes:
      - "./db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
    networks:
      - my-net

  web:
    image: python:3.8
    ports:
      - "80:8000"
    depends_on:
      - db
    volumes:
      - ./data:/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
    command: >
      bash -c ""
    networks:
      - my-net

networks:
  my-net:
