version: "3.3"
services:
  db:
    image: postgres:14.3
    ports:
      - "5432:5432"
    volumes:
      - "~/db:/var/lib/postgresql/data"
      - ./data:/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
    networks:
      - my-net

  back:
    build: ./src/
    ports:
      - "8000:8000"
    working_dir: /project
    depends_on:
      - db
    volumes:
      - ./data:/data
      - ./src:/project
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
    command: >
      bash -c "python api.py"
    networks:
      - my-net

  front:
    build: ./front/
    ports:
      - "5173:5173"
    networks:
      - my-net
    depends_on:
      - back
    command: >
      bash -c "npx vite --host"

networks:
  my-net:
